- README.md
- src/api/xxAMIDOxx.xxSTACKSxx.API/appsettings.json
- src/api/xxAMIDOxx.xxSTACKSxx.Worker/ChangeFeedListener.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Worker/ItemChangedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Worker/Startup.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Worker/appsettings.json
- src/api/xxAMIDOxx.xxSTACKSxx.Worker/xxAMIDOxx.xxSTACKSxx.Worker.csproj
[3167 -  Publish a message from the changefeed listener]
- Add a dependency on the Amido.Stacks.Messaging.Azure.ServiceBus in the changefeed listener Azure function
- Updated README
- We want to showcase simple publishing to ServiceBus using the Amido.Stacks.Messaging.Azure.ServiceBus package in a function setting
> 3167 -  Publish a message from the changefeed listener

- src/api/xxAMIDOxx.xxSTACKSxx.API.ComponentTests/xxAMIDOxx.xxSTACKSxx.API.ComponentTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Application.CommandHandlers/xxAMIDOxx.xxSTACKSxx.Application.CommandHandlers.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/Logging/LogAdapter.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/StacksListener.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/Startup.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/appsettings.json
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/host.json
- src/api/xxAMIDOxx.xxSTACKSxx.Listener/xxAMIDOxx.xxSTACKSxx.Listener.csproj
[3179 - Receive message from topic with Azure Function Service Bus trigger]
A new Azure Function that has a service bus trigger which receives `MenuCreatedEvent` sent from the API
We want to show how to use the IMessageReader from the ASB messaging package to read the `StacksCloudEvent<T>` sent to the topic from the API
We've added a new Azure Function project which is a separate executable from the Worker Azure Function and the WebAPI project. The project has a dependency on the events and ASB messaging packages.
> Receive message from topic with Azure Function Service Bus trigger

- src/api/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/MenuCreatedEventHandler.cs
- src/api/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/Program.cs
- src/api/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/appsettings.json
- src/api/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker.csproj
[3180 - Build a background worker to receive messages from Service Bus]
A new project that contains a background worker that receives a message from Service Bus
We want to showcase how to use the Amido.Stacks.Messaging.Azure.ServiceBus package to listen for messages from Service Bus when Azure Functions are not appropriate.
> Add background worker listener

- build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
- build/azDevOps/azure/templates/steps/build/build-function.yml
- deploy/azure/app/kube/outputs.tf
- deploy/azure/app/servicebus/function.tf
- deploy/azure/app/servicebus/outputs.tf
- src/functions/Dockerfile
The servicebus has required some new infrastructure:
- 2 x Azure functions
- 2 x Storage accounts
- Servicebus with topic and 2 subscriptions
These have been added in using a local Terraform module.
The deployment has also been updated so that the two functions are created as Docker containers, pushed to the repository and then deployed into the functions.
This is required to support the events for a CQRS website
Added new Terraform module which is run as part of the two build for Dev and Prod.
Tests have not yet been written for the functions
Notes for QA
> [3188] Build pipeline for service bus

- README.md
- src/api/xxAMIDOxx.xxSTACKSxx.API/Startup.cs
[3379 - Update README]
A small update to the README outlying the structure and usage
Add a bit more clarity to the structure of our code
Notes for QA
> Update project repository link and README

- .gitignore
- src/api/xxAMIDOxx.xxSTACKSxx.API/appsettings.json
- src/functions/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/StacksListenerTests.cs
- src/functions/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/TestOperationContext.cs
- src/functions/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests.csproj
- src/functions/xxAMIDOxx.xxSTACKSxx.Listener.sln
- src/functions/xxAMIDOxx.xxSTACKSxx.Listener/StacksListener.cs
- src/functions/xxAMIDOxx.xxSTACKSxx.Worker.UnitTests/ChangeFeedListenerTests.cs
- src/functions/xxAMIDOxx.xxSTACKSxx.Worker.UnitTests/xxAMIDOxx.xxSTACKSxx.Worker.UnitTests.csproj
- src/functions/xxAMIDOxx.xxSTACKSxx.Worker.sln
- src/functions/xxAMIDOxx.xxSTACKSxx.Worker/appsettings.json
- src/worker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/appsettings.json
- src/worker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker.csproj
Added unit tests to functions
Listener and changefeed functions had unit tests added.
All other tests are executed inside Messaging Package
> Added unit tests to functions

- README.md
[3239 - Add template information to README]
Documentation for the installation and usage of templates
People re-writing the CLI or just using the templates themselves have to know how to use our templates.
Notes for QA
> Add template information to README

- build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
- build/azDevOps/azure/azuredevops-vars.yml
📲 What
Move the top level variable out of the main pipeline file into a separate file.
AB#3594
🤔 Why
The Stacks CLI currently performs a search and replace on the template file to change the values based on the user input to the CLI. This is brittle because the original value could change and the CLI would not replace the value correctly.
By making this a separate file the CLI is able to build up the file as needed, without the need for any text replacements.
🛠 How
All of the variables are written to the variable template file, azuredevops-vars.yaml. This is included in the main build file, e.g.
variables:
- template: azuredevops-vars.yml
👀 Evidence
The builds are working as before
🕵️ How to test
Notes for QA
✅ Acceptance criteria Checklist
Code peer reviewed?
Documentation has been …
> [3594] Use variable template for stacks-dotnet-cqrs-event

- .template.config/template.json
3389 - Build template for Event Hub function - .Net
Exclude whole folder for listener function that is not selected.
> 3389 - Build template for Event Hub function - .Net

- .template.config/dotnetcli.host.json
- README.md
- src/api/.template.config/dotnetcli.host.json
- src/functions/func-aeh-listener/.template.config/dotnetcli.host.json
- src/functions/func-asb-listener/.template.config/dotnetcli.host.json
- src/worker/.template.config/dotnetcli.host.json
3902 - Unify CLI template arguments
We want the CLI arguments to be unified between all templates
So we can have consistency throughout our offering
Notes for QA
> Unify CLI arguments

- build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
3968 - Update versioning for package
In preparation for .NET 6 we want to version the current packages with their current .NET runtime
Why it's needed, background context.
Notes for QA
> Update major version

- src/api/xxAMIDOxx.xxSTACKSxx.API.ComponentTests/xxAMIDOxx.xxSTACKSxx.API.ComponentTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.API.ContractTests/xxAMIDOxx.xxSTACKSxx.API.ContractTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.API/xxAMIDOxx.xxSTACKSxx.API.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Application.CommandHandlers/xxAMIDOxx.xxSTACKSxx.Application.CommandHandlers.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Application.QueryHandlers/xxAMIDOxx.xxSTACKSxx.Application.QueryHandlers.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Common.UnitTests/xxAMIDOxx.xxSTACKSxx.Common.UnitTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Common/xxAMIDOxx.xxSTACKSxx.Common.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Domain.UnitTests/xxAMIDOxx.xxSTACKSxx.Domain.UnitTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Domain/xxAMIDOxx.xxSTACKSxx.Domain.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/DependencyRegistration.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/xxAMIDOxx.xxSTACKSxx.Infrastructure.csproj
- src/functions/func-aeh-listener/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events.csproj
- src/functions/func-aeh-listener/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests.csproj
- src/functions/func-aeh-listener/xxAMIDOxx.xxSTACKSxx.Listener/xxAMIDOxx.xxSTACKSxx.Listener.csproj
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events.csproj
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests.csproj
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Listener/Startup.cs
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Listener/xxAMIDOxx.xxSTACKSxx.Listener.csproj
- src/functions/func-cosmosdb-worker/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events.csproj
- src/functions/func-cosmosdb-worker/xxAMIDOxx.xxSTACKSxx.Worker.UnitTests/xxAMIDOxx.xxSTACKSxx.Worker.UnitTests.csproj
- src/functions/func-cosmosdb-worker/xxAMIDOxx.xxSTACKSxx.Worker/xxAMIDOxx.xxSTACKSxx.Worker.csproj
- src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj
- src/worker/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events/xxAMIDOxx.xxSTACKSxx.Application.CQRS.Events.csproj
- src/worker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker/xxAMIDOxx.xxSTACKSxx.BackgroundWorker.csproj
Fix vulnerabilites and bump dependencies
Changes:
- api: fix snyk vulnerabilities and update packages
- func-aeh: fix snyk vulnerabilities and update packages
- func-asb: fix snyk vulnerabilities and update packages
- func-worker: fix snyk vulnerabilities and update packages
- tests-functional: fix snyk vulnerabilities and update packages
- background-worker: fix snyk vulnerabilities and update packages
Fix vulnerabilities
Update old packages
Notes for QA
> Fix vulnerabilities and bump dependencies

- src/functions/func-aeh-listener/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests/xxAMIDOxx.xxSTACKSxx.Listener.UnitTests.csproj
[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
Update the `xxAMIDOxx.xxSTACKSxx.Listener.UnitTests` project to use the latest version of `Amido.Stacks.Messaging.Azure.EventHub`
To resolve vulnerabilities identified by Snyk
Notes for QA
> Snyk fix CVE 2018 8292

- .snyk
Ignore SNYK-DOTNET-SYSTEMIOCOMPRESSIONZIPFILE-174570 vulnerability for 30 days
Ignore vulnerability for 30 days as it is part of CosmosDB@3.0.10 which doesn't have a higher production ready version
Notes for QA
> SNYK-DOTNET-SYSTEMIOCOMPRESSIONZIPFILE-174570

- src/api/xxAMIDOxx.xxSTACKSxx.Domain/xxAMIDOxx.xxSTACKSxx.Domain.csproj
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/xxAMIDOxx.xxSTACKSxx.Infrastructure.csproj
4277 - Add DynamoDB package to CQRS template
Adding references to the DynamoDB package
As part of Cycle 8 of Stacks we want to offer connectivity to DynamoDB as a data store.
Notes for QA
> Add DynamoDB package references

- .template.config/template.json
- src/api/xxAMIDOxx.xxSTACKSxx.Domain.UnitTests/DynamoDbCategoryConverterTests.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Domain/MenuAggregateRoot/Aggregate/Menu.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Domain/MenuAggregateRoot/Entities/Converters/DynamoDbCategoryConverter.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/DependencyRegistration.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/Repositories/DynamoDbMenuRepository.cs
4347 - Initial DynamoDB implementation
- Changes to the domain object needed for DynamoDB
- DI setup for DynamoDB
- Conditional compilation setup for DynamoDB
- Making relevant changes to the DynamoDB repository
We want to be able to perform CRUD operations to DynamoDB as a data store
Notes for QA
> Initial DynamoDB implementation

- README.md
4359 - Update README with DynamoDB information
Add details on how to configure DynamoDB if you want to run the project locally.
Why it's needed, background context.
Notes for QA
> Update README with DynamoDB information

- README.md
- src/api/xxAMIDOxx.xxSTACKSxx.API/appsettings.json
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/DependencyRegistration.cs
- src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/xxAMIDOxx.xxSTACKSxx.Infrastructure.csproj
[AB#4519](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4519) Update README to reflect Secret requirements for AWS SQS
Update README to reflect Secret requirements for AWS SQS
Update README to reflect Secret requirements for AWS SQS
N/A
Notes for QA
> AB#4519 Update README to reflect Secret requirements for AWS SQS

- src/api/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests/HandlerTests.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/CategoryCreatedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/CategoryDeletedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/CategoryUpdatedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/CosmosDbChangeFeedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuCreatedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuDeletedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuItemCreatedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuItemDeletedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuItemUpdatedEvent.cs
- src/api/xxAMIDOxx.xxSTACKSxx.CQRS/Events/MenuUpdatedEvent.cs
[AB#4543](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4543) - Implement test coverage improvements in stacks-dotnet-cqrs-events
Increase CQRS objects test coverage
To increase code coverage for the CQRS project
Notes for QA
> AB#4543 - Implement test coverage improvements in stacks-dotnet-cqrs-events

- build/azDevOps/azure/api-contract-tests.yml
- src/api/xxAMIDOxx.xxSTACKSxx.API.ContractTests/appsettings.json
- src/functions/func-aeh-listener/xxAMIDOxx.xxSTACKSxx.Listener/xxAMIDOxx.xxSTACKSxx.Listener.csproj
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Listener/Startup.cs
- src/functions/func-asb-listener/xxAMIDOxx.xxSTACKSxx.Listener/xxAMIDOxx.xxSTACKSxx.Listener.csproj
- src/functions/func-cosmosdb-worker/xxAMIDOxx.xxSTACKSxx.Worker/xxAMIDOxx.xxSTACKSxx.Worker.csproj
[AB#4562](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4562) Azure Service Bus Listener - Issue on start up
Logger failing to instantiate on start up
Fix the issue so the functions can start up with Serilog
Notes for QA
> AB#4562 Azure Service Bus Listener - Issue on start up
